{% set pyproject = load_file_data('../pyproject.toml', from_recipe_dir=True) %}
{% set name = pyproject.get('project').get('name') %}
{% set description = pyproject.get('project').get('description') %}
{% set version = environ.get('SETUPTOOLS_SCM_PRETEND_VERSION', '0.0.0.dev') %}
{% set license = pyproject.get('project').get('license') %}
{% set home = pyproject.get('project', {}).get('urls', {}).get('Homepage', '') %}
{% set build_deps = pyproject.get("build-system", {}).get("requires", []) %}
{% set deps = pyproject.get('project', {}).get('dependencies', []) %}
{% set conda_deps = pyproject.get('tool', {}).get('conda', {}).get('environment', {}).get('dependencies',[]) %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  script_env:
    - CC=gcc # [win]
    # Force static build on Windows to allow skipping run export of m2w64 stdlib
    - LDFLAGS=-static -static-libgcc -static-libgfortran   # [win]
    # to correct in windows-latest libmamba Failed to load subdir: Download error (35) SSL connect error
    # - SSL_NO_VERIFY=1
  ignore_run_exports_from:
    # Avoid automatic run export of m2w64 stdlib on windows (that forces hard regression of msvc libs)
    - {{ compiler('c') }} # [win]
    - {{ compiler('cxx') }} # [win]
  preserve_egg_dir: True
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-build-isolation -vv

requirements:
  host:
    - python
    {% for dep in build_deps %}
    - {{ dep }}
    {% endfor  %}
  build:
    - python
    {% for dep in build_deps %}
    - {{ dep }}
    {% endfor  %}
    - {{ compiler('fortran') }}  # [not win]
    - {{ compiler('c') }}
    - charset-normalizer
  run:
    - python
    {% for dep in deps + conda_deps %}
    - {{ dep }}
    {% endfor %}
    - charset-normalizer

test:
  requires:
    - pytest
    {% for dep in deps + conda_deps %}
    - {{ dep }}
    {% endfor %}
  imports:
    - {{ name }}
  source_files:
    - test/test_*.py
    - test/data/**
  commands:
   - cd test
   - pytest -v --ignore=test_complet.py --ignore=test_LightTuto.py --ignore=test_RatpScene.py

about:
  home: {{ home }}
  license: {{ license }}
  summary: {{ description }}

extra:
  recipe-maintainers:
    - pradal
    - baugetfa
