name: build_publish_anaconda

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    uses: openalea/github-action-conda-build/.github/workflows/conda-package-build.yml@main
    secrets:
      anaconda_token: ${{ secrets.ANACONDA_TOKEN }}
    with:
      operating-system: '[ ubuntu-latest , macos-13 , windows-latest]'
      python-minor-version: "[10, 11, 12]"
      build-options: ""
